---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/go-httpbin/
  - ../../base/mockserver/

images:
  - name: quay.io/rh_integration/go-httpbin
    newName: docker.io/mccutchen/go-httpbin
    newTag: latest
